# Generated by Django 3.2.2 on 2021-12-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('us_id', models.AutoField(primary_key=True, serialize=False)),
                ('us_name', models.CharField(max_length=300)),
                ('us_email', models.EmailField(max_length=300)),
                ('us_password', models.CharField(max_length=300)),
                ('us_type', models.CharField(max_length=100)),
                ('us_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('trash', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user_types',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('type_name', models.CharField(max_length=250)),
                ('trash', models.BooleanField(default=False)),
            ],
        ),
    ]
