# Generated by Django 3.2.2 on 2021-12-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syspos', '0003_auto_20211223_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_customer',
            name='cus_first_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
