# Generated by Django 3.2.2 on 2021-12-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syspos', '0004_alter_tbl_customer_cus_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_customer',
            old_name='cus_first_name',
            new_name='cus_name',
        ),
        migrations.RemoveField(
            model_name='tbl_customer',
            name='cus_image',
        ),
        migrations.RemoveField(
            model_name='tbl_customer',
            name='cus_last_name',
        ),
        migrations.RemoveField(
            model_name='tbl_customer',
            name='cus_password',
        ),
        migrations.AlterField(
            model_name='tbl_customer',
            name='cus_mobile',
            field=models.IntegerField(null=True),
        ),
    ]
