# Generated by Django 3.2.2 on 2021-12-29 04:17

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('syspos', '0005_auto_20211228_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_customer',
            name='cus_remark',
        ),
        migrations.RemoveField(
            model_name='tbl_customer',
            name='cus_vat',
        ),
        migrations.AddField(
            model_name='tbl_customer',
            name='cus_loyalty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tbl_customer',
            name='cus_mobile',
            field=phone_field.models.PhoneField(max_length=31, null=True),
        ),
    ]
