# Generated by Django 3.2.2 on 2021-12-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syspos', '0006_auto_20211229_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_customer',
            name='cus_loyalty',
            field=models.BooleanField(default=True),
        ),
    ]
