# Generated by Django 3.2.2 on 2021-12-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syspos', '0007_alter_tbl_customer_cus_loyalty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_customer',
            name='cus_join_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
