# Generated by Django 3.2.2 on 2021-12-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syspos', '0009_alter_tbl_customer_cus_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_customer',
            name='cus_loyalty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tbl_customer',
            name='trash',
            field=models.BooleanField(default=False),
        ),
    ]
