# Generated by Django 3.2.2 on 2021-12-29 10:09

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('syspos', '0010_auto_20211229_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='us_phone',
            field=phone_field.models.PhoneField(max_length=31, null=True),
        ),
    ]
