# Generated by Django 3.2.2 on 2021-12-30 11:24

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('syspos', '0012_auto_20211230_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_customer',
            name='cus_email',
            field=models.EmailField(max_length=300, null=True),
        )
    ]
