# Generated by Django 3.2.2 on 2021-12-30 11:32

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('syspos', '0013_auto_20211230_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_customer',
            name='cus_mobile',
            field=phone_field.models.PhoneField(max_length=31, null=True),
        ),
    ]
