# Generated by Django 3.2.2 on 2021-12-31 10:29

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('syspos', '0014_alter_tbl_customer_cus_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_supplier',
            fields=[
                ('sup_id', models.AutoField(primary_key=True, serialize=False)),
                ('sup_company', models.CharField(max_length=200)),
                ('sup_pin', models.CharField(max_length=200)),
                ('sup_name', models.CharField(max_length=500)),
                ('sup_country', models.CharField(max_length=200)),
                ('sup_vat', models.CharField(max_length=300, null=True)),
                ('sup_gst', models.CharField(max_length=200, null=True)),
                ('sup_email', models.EmailField(max_length=300)),
                ('sup_phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('sup_address', models.CharField(max_length=300)),
                ('sup_city', models.CharField(max_length=200)),
                ('sup_state', models.CharField(max_length=300)),
                ('sup_description', models.CharField(max_length=600, null=True)),
                ('sup_date', models.DateTimeField(auto_now_add=True)),
                ('trash', models.BooleanField(default=False)),
            ],
        ),
    ]
