# Generated by Django 3.2.2 on 2022-01-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syspos', '0017_tbl_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_warehouse',
            fields=[
                ('wr_id', models.AutoField(primary_key=True, serialize=False)),
                ('wr_name', models.CharField(max_length=300, null=True)),
                ('wr_address', models.TextField(null=True)),
                ('wr_building', models.CharField(max_length=100, null=True)),
                ('wr_description', models.TextField(null=True)),
                ('wr_image', models.ImageField(blank=True, null=True, upload_to='warehouses')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('trash', models.BooleanField(default=True)),
            ],
        ),
    ]
